// Generate the web app's typed media index from media/library.json.
//
// The manager owns folders. Web code selects those folders by generated slug
// types, so renaming or deleting a referenced folder breaks typecheck/build until
// the explicit selector is updated. EXIF stays manager-only; the site receives
// only location and folder membership.

import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

import { validateFolderAssignments, validateFolderTree } from "./folders.mjs";
import { libraryPath, mediaTsPath } from "./paths.mjs";

export function generateMedia() {
  const library = JSON.parse(readFileSync(libraryPath, "utf8"));
  const folders = library.folders;
  const items = library.items;
  validateFolderTree(folders);
  if (!items || typeof items !== "object" || Array.isArray(items)) {
    throw new Error("library items must be an object");
  }

  const byFile = ([, a], [, b]) => a.file.localeCompare(b.file);
  const entries = Object.entries(items);
  const photos = entries.filter(([, item]) => item.type !== "video").toSorted(byFile);
  const videos = entries.filter(([, item]) => item.type === "video").toSorted(byFile);
  const errors = [];
  const imports = [];
  const imageEntries = [];
  const imageMetaEntries = [];
  const videoEntries = [];
  const videoMetaEntries = [];

  photos.forEach(([id, item], index) => {
    checkItem(errors, id, item, folders);
    if (!isCanonicalPhoto(item)) errors.push(`${id}: photo source is not 4:3 or 3:4`);
    imports.push(`import p${index} from "@media/${item.file}?url";`);
    imageEntries.push(
      `  ${JSON.stringify(id)}: { src: p${index}, width: ${item.width}, height: ${item.height} },`,
    );
    imageMetaEntries.push(`  ${JSON.stringify(id)}: ${JSON.stringify(metaOf(item))},`);
  });

  videos.forEach(([id, item], index) => {
    checkItem(errors, id, item, folders);
    if (!item.poster) errors.push(`${id}: video has no poster`);
    imports.push(`import v${index} from "@media/${item.file}?url";`);
    if (item.poster) imports.push(`import vp${index} from "@media/${item.poster}?url";`);
    videoEntries.push(`  ${JSON.stringify(id)}: { src: v${index}, poster: vp${index} },`);
    videoMetaEntries.push(`  ${JSON.stringify(id)}: ${JSON.stringify(metaOf(item))},`);
  });

  if (errors.length) throw new Error(`library.json problems:\n  ${errors.join("\n  ")}`);

  const folderEntries = Object.entries(folders).map(
    ([slug, folder]) =>
      `  ${JSON.stringify(slug)}: ${JSON.stringify({ label: folder.label, parent: folder.parent ?? null })},`,
  );

  const out = `// Generated by the media manager (apps/media) — do not edit by hand.
// Edit media/library.json through the manager, then regenerate this file.
${imports.join("\n")}

export const folders = {
${folderEntries.join("\n")}
} as const;

export type FolderSlug = keyof typeof folders;

export const folderSlugs = ${JSON.stringify(Object.keys(folders))} as const;

export const images = {
${imageEntries.join("\n")}
};

export type SiteImage = { src: string; width: number; height: number };

export type ImageKey = keyof typeof images;

export const imageKeys = ${JSON.stringify(photos.map(([id]) => id))} as const;

export type MediaMeta = {
  location: string;
  folders: FolderSlug[];
};

export const imageMeta = {
${imageMetaEntries.join("\n")}
} satisfies Record<ImageKey, MediaMeta>;

export type SiteVideo = { src: string; poster: string };

export const videos = {
${videoEntries.join("\n")}
};

export type VideoKey = keyof typeof videos;

export const videoKeys = ${JSON.stringify(videos.map(([id]) => id))} as const;

export const videoMeta = {
${videoMetaEntries.join("\n")}
} satisfies Record<VideoKey, MediaMeta>;
`;

  writeFileSync(mediaTsPath, out);
  return { photos: photos.length, videos: videos.length };
}

function checkItem(errors, id, item, folders) {
  try {
    validateFolderAssignments(item.folders, folders, id);
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }
}

function metaOf(item) {
  return {
    location: item.location ?? "",
    folders: [...item.folders].toSorted((a, b) => a.localeCompare(b)),
  };
}

function isCanonicalPhoto(item) {
  if (!item.width || !item.height) return false;
  const aspect = item.width / item.height;
  return Math.abs(aspect - 4 / 3) < 0.01 || Math.abs(aspect - 3 / 4) < 0.01;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { photos, videos } = generateMedia();
  console.log(`media.gen.ts: ${photos} photos, ${videos} videos`);
}
